### ISSUE TITLE
Investigate blank page displaying in example app

### ISSUE THREAD

**Issue by elmarti** [elmarti/meteor-video-chat-example#12]
As per the issue created in the meteor-video-chat project, investigate blank screen displaying. 

https://github.com/elmarti/meteor-video-chat/issues/62

**Comment by elmarti** [comment]
It appears to be working fine on my local machine, as for the files, in order to make it easier to integrate ReactJS with SSR and to decouple it slightly, all files can be found in the "modules" folder. I did originally have plans to create example projects with all 3 client side libraries, but didn't out of lack of interest from users. If you like I can look at making one in Blaze.

**Comment by elmarti** [comment]
I've started a new Blaze based project that will be closer to the boilerplate project.
https://github.com/elmarti/blaze-video-chat
It's currently using 2.0.0-alpha, but I will be releasing the 2.0.0 version this week so it will be upgraded in turn

**Comment by elmarti** [comment]
this blaze project should be completed in a day or two

**Comment by sir007** [comment]
Great elmarti,
i'm waiting for this blaze project  with a good example !

Thanks

**Comment by elmarti** [comment]
Tomorrow Meteor Video Chat will be integrated with my new WebRTC project and it will then follow a stable API and hopefully grow as a project https://github.com/RTCFly/RTCFly. 

So if all goes well in publishing it, the `blaze-video-chat` should be completed tomorrow.

**Comment by sir007** [comment]
Hi elmarti,
is the blaze-video-chat available?

**Comment by elmarti** [comment]
Hi @sir007, nearly there. The 2.0 version of the video chat was released today so most work has gone onto that, but it should be done by tomorrow. 

As for this issue, this project has had a complete upgrade and appears to be working fine.

**Comment by elmarti** [comment]
@sir007 The application blaze-video-chat is now usable, a few bugs to iron how, but the WebRTC workflow is working fine. https://github.com/elmarti/blaze-video-chat
